# Generated by Django 4.1.4 on 2024-07-17 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=1)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create', to=settings.AUTH_USER_MODEL)),
                ('updatedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SMSModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageSent', models.IntegerField(default=0)),
                ('allowedMessages', models.IntegerField(default=0)),
                ('isActive', models.BooleanField(default=1)),
                ('status', models.BooleanField(default=1)),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VersionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versionNumber', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('dateOfRelease', models.DateTimeField()),
                ('askUpgrade', models.BooleanField(default=1)),
                ('status', models.BooleanField(default=1)),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdBy', to=settings.AUTH_USER_MODEL)),
                ('updatedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updatedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('organisation', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=1)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='_create', to=settings.AUTH_USER_MODEL)),
                ('updatedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='_update', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MasterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.DateTimeField()),
                ('activity', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=1)),
                ('mobileUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.userregistration')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='analytics-images')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('predictionType', models.CharField(max_length=100)),
                ('predictionColor', models.CharField(max_length=100)),
                ('feedbackType', models.CharField(max_length=100)),
                ('feedbackColor', models.CharField(max_length=100)),
                ('location', models.TextField(blank=True, null=True)),
                ('isFlash', models.BooleanField(default=0)),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=1)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='create', to='users.userregistration')),
                ('updatedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='update', to='users.userregistration')),
            ],
        ),
    ]
