# Generated by Django 4.1.3 on 2022-12-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_createdby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.BooleanField(default=1),
        ),
    ]
