# Generated by Django 4.1.3 on 2022-12-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
