# Generated by Django 4.1.3 on 2022-12-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_masterlog_mobileuser_alter_masterlog_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageSent', models.IntegerField(default=0)),
                ('allowedMessages', models.IntegerField(default=0)),
                ('isActive', models.BooleanField(default=1)),
                ('status', models.BooleanField(default=1)),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
