# Generated by Django 4.1.3 on 2022-12-23 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_smsmodule'),
        ('users', '0009_alter_customuser_mobile'),
    ]

    operations = [
    ]
