# Generated by Django 4.1.3 on 2022-12-26 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_merge_0008_smsmodule_0009_alter_customuser_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versionNumber', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('dateOfRelease', models.DateTimeField()),
                ('askUpgrade', models.BooleanField(default=1)),
                ('status', models.BooleanField(default=1)),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdBy', to=settings.AUTH_USER_MODEL)),
                ('updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='updatedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
