# Generated by Django 4.1.3 on 2022-12-26 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0011_versionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionlog',
            name='updatedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updatedBy', to=settings.AUTH_USER_MODEL),
        ),
    ]
