# Generated by Django 4.1.3 on 2023-01-09 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_mobile'),
        ('users', '0012_alter_versionlog_updatedby'),
    ]

    operations = [
    ]
