# Generated by Django 4.1.3 on 2023-01-11 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_analysis_prediction_remove_analysis_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Analysis',
        ),
    ]
