# Generated by Django 4.1.3 on 2023-01-11 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_merge_20230109_1521'),
        ('users', '0017_alter_analysis_createdat'),
    ]

    operations = [
    ]
