# Generated by Django 4.1.3 on 2023-01-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_merge_20230111_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='isFlash',
            field=models.BooleanField(default=0),
        ),
    ]
