# Generated by Django 4.1.3 on 2023-01-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_analysis_isflash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='mobile',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
