# Generated by Django 4.1.3 on 2024-02-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_userregistration_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='createdAt',
            field=models.DateTimeField(),
        ),
    ]
