name: Django CI

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no -i /tmp/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd /home/tw-usermanagement-practice || exit 1
            if [ -d ".git" ]; then
              git fetch origin || exit 1
              git reset --hard origin/development || exit 1
            else
              git clone -b development ${{ secrets.URL }} . || exit 1
            fi
            docker build -f 3m-usermanagement/usermanagement/Dockerfile -t usermanagement_app . || exit 1
            docker stop usermanagement || true
            docker rm usermanagement || true
            docker run -d -p 8040:8000 --name usermanagement usermanagement_app || exit 1
          EOF
