name: Django CI

on: [push]
  # push:
  #   branches: [ "development" ]
  # pull_request:
  #   branches: [ "development" ]

jobs: 
  deploy:
    if: github.ref_name == 'development'
    runs-on: ubuntu-latest
    env:
      CI_REGISTRY_IMAGE: ${{ secrets.CI_REGISTRY_IMAGE }}
      TAG_LATEST: ${{ secrets.CI_REGISTRY_IMAGE }}/${{ github.ref_name }}:latest
      TAG_COMMIT: ${{ secrets.CI_REGISTRY_IMAGE }}/${{ github.ref_name }}:${{ github.sha }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.ID_RSA }}

      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Print environment variables for debugging
        run: |
          echo "CI_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE"
          echo "TAG_LATEST: $TAG_LATEST"
          echo "TAG_COMMIT: $TAG_COMMIT"

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "docker pull $TAG_COMMIT"
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "docker container rm -f 3m_app || true"
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "docker run -d -p 8040:8000 --name 3m_app $TAG_COMMIT"
