name: Django CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install -r 3m-usermanagement/usermanagement/requirements.txt

      - name: Run tests
        run: |
          python 3m-usermanagement/usermanagement/manage.py test

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -f 3m-usermanagement/usermanagement/Dockerfile -t usermanagement_app 3m-usermanagement/usermanagement

  deploy:
    if: github.ref_name == 'development'
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.ID_RSA }}

      - name: Set SSH key permissions
        # run: chmod 600 ~/.ssh/id_rsa

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.1
        with:
          source: "."
          target: /home/tw-usermanagement-practice
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.ID_RSA }}
          port: ${{ secrets.SERVER_PORT }}

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.ID_RSA }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /home/tw-usermanagement-practice
            docker build -t usermanagement_app .
            docker stop usermanagement || true
            docker rm usermanagement || true
            docker run -d -p 8040:8000 --name usermanagement usermanagement_app
