name: Django CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install -r 3m-usermanagement/usermanagement/requirements.txt

      - name: Run tests
        run: |
          python 3m-usermanagement/usermanagement/manage.py test

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -f 3m-usermanagement/usermanagement/Dockerfile -t usermanagement_app 3m-usermanagement/usermanagement

  deploy:
    if: github.ref_name == 'development'
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Set permissions for SSH key
        run: |
          echo "${{ secrets.ID_RSA }}" > /tmp/id_rsa
          chmod 600 /tmp/id_rsa

      - name: Debug SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no -i /tmp/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "echo 'SSH connection established'"

      - name: Copy files to server
        run: |
          scp -i /tmp/id_rsa -P ${{ secrets.SERVER_PORT }} -r . ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/tw-usermanagement-practice

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no -i /tmp/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd /home/tw-usermanagement-practice
            docker build -t usermanagement_app .
            docker stop usermanagement || true
            docker rm usermanagement || true
            docker run -d -p 8040:8000 --name usermanagement usermanagement_app
          EOF
